local stub = require("wow_stub")

local DEFAULT_ORDER = { "warrior", "paladin", "hunter", "rogue", "priest", "shaman", "mage", "warlock", "druid",
    "weapon", "consumable", "world", "other" }

T.test("Seed populates the 13 defaults in shipped order, once", function()
    local BL = stub.LoadAddon()
    T.deq(BL.Categories.Order(), DEFAULT_ORDER)
    T.eq(T.count(BL.DB.categories), 13)
    local priest = BL.Categories.Get("priest")
    T.eq(priest.name, "Priest")
    T.eq(priest.builtin, true)
    T.eq(priest.deletable, true)
    T.eq(priest.hidden, false)
    T.eq(priest.consolidate, false)
    T.near(priest.color[1], 1, 0.001)
    T.eq(BL.Categories.Get("other").deletable, false)
    T.eq(BL.Categories.Get("warrior").icon, "Interface\\Icons\\Ability_Warrior_Rampage")

    BL.Categories.Delete("mage")
    BL.Categories.Seed()
    T.isnil(BL.Categories.Get("mage"), "second Seed is a no-op")
end)

T.test("class colours come from RAID_CLASS_COLORS at seed time", function()
    local BL = stub.LoadAddon()
    local mage = BL.Categories.Get("mage")
    T.near(mage.color[1], 0.25, 0.001)
    T.near(mage.color[2], 0.78, 0.001)
end)

T.test("Create appends before Other and bumps nextCustomId", function()
    local BL = stub.LoadAddon()
    local fired = 0
    BL.On("CATEGORIES_CHANGED", function() fired = fired + 1 end)
    local id = BL.Categories.Create("Trinkets", { 0.1, 0.2, 0.3 })
    T.eq(id, "custom-1")
    T.eq(BL.DB.nextCustomId, 2)
    local order = BL.Categories.Order()
    T.eq(order[#order], "other")
    T.eq(order[#order - 1], "custom-1")
    local rec = BL.Categories.Get(id)
    T.eq(rec.name, "Trinkets")
    T.eq(rec.builtin, false)
    T.eq(rec.deletable, true)
    T.deq(rec.color, { 0.1, 0.2, 0.3 })
    T.eq(fired, 1)
    T.eq(BL.Categories.Create("Second"), "custom-2")
end)

T.test("Rename/SetColor/SetHidden/SetConsolidate write the record and fire once each", function()
    local BL = stub.LoadAddon()
    local fired = 0
    BL.On("CATEGORIES_CHANGED", function() fired = fired + 1 end)
    BL.Categories.Rename("priest", "Holy folks")
    BL.Categories.SetColor("priest", { 0.5, 0.5, 0.5 })
    BL.Categories.SetHidden("priest", true)
    BL.Categories.SetConsolidate("priest", true)
    local p = BL.Categories.Get("priest")
    T.eq(p.name, "Holy folks")
    T.deq(p.color, { 0.5, 0.5, 0.5 })
    T.eq(p.hidden, true)
    T.eq(p.consolidate, true)
    T.eq(fired, 4)
    T.falsy(BL.Categories.Rename("nope", "x"))
end)

T.test("Move shifts within the order, clamps, and never moves Other", function()
    local BL = stub.LoadAddon()
    T.truthy(BL.Categories.Move("paladin", -1))
    T.eq(BL.Categories.Order()[1], "paladin")
    T.eq(BL.Categories.Order()[2], "warrior")
    T.falsy(BL.Categories.Move("paladin", -1), "already first")
    T.falsy(BL.Categories.Move("other", -1))
    T.falsy(BL.Categories.Move("other", 1))
    T.falsy(BL.Categories.Move("world", 1), "cannot move below Other")
    T.truthy(BL.Categories.Move("world", -1))
    local o = BL.Categories.Order()
    T.eq(o[#o], "other")
    T.eq(o[#o - 1], "consumable")
    T.eq(o[#o - 2], "world")
end)

T.test("Delete refuses Other and unknowns, removes the record, redirects overrides and learned", function()
    local BL = stub.LoadAddon()
    BL.DB.overrides["Arcane Intellect"] = "mage"
    BL.DB.overrides["Food"] = "consumable"
    BL.DB.learned["Frost Armor"] = "mage"
    T.falsy(BL.Categories.Delete("other"))
    T.falsy(BL.Categories.Delete("nope"))
    T.truthy(BL.Categories.Delete("mage"))
    T.isnil(BL.Categories.Get("mage"))
    T.falsy(tContains(BL.Categories.Order(), "mage"))
    T.eq(BL.DB.overrides["Arcane Intellect"], "other")
    T.eq(BL.DB.overrides["Food"], "consumable")
    T.eq(BL.DB.learned["Frost Armor"], "other")
    T.eq(BL.Categories.Resolve("mage"), "other")
    T.eq(BL.Categories.Resolve("priest"), "priest")
    T.falsy(BL.Categories.Exists("mage"))
end)

T.test("ResetToDefault restores missing built-ins in shipped order and keeps customs after them", function()
    local BL = stub.LoadAddon()
    BL.Categories.Delete("hunter")
    BL.Categories.Delete("rogue")
    BL.Categories.Rename("priest", "Renamed")
    local c1 = BL.Categories.Create("Custom A")
    local c2 = BL.Categories.Create("Custom B")
    BL.Categories.Move(c2, -1) -- B before A
    BL.Categories.Move("druid", -1)
    BL.DB.overrides["Aspect of the Hawk"] = "other"
    BL.DB.history[1] = { buffName = "x", from = "a", to = "b", time = 1 }

    BL.Categories.ResetToDefault()

    local expected = {}
    for _, id in ipairs(DEFAULT_ORDER) do expected[#expected + 1] = id end
    table.insert(expected, #expected, c2) -- customs sit before Other
    table.insert(expected, #expected, c1)
    T.deq(BL.Categories.Order(), expected)
    T.eq(BL.Categories.Get("hunter").name, "Hunter")
    T.eq(BL.Categories.Get("priest").name, "Renamed", "existing built-ins untouched")
    T.eq(BL.DB.overrides["Aspect of the Hawk"], "other", "overrides untouched")
    T.eq(#BL.DB.history, 1)
end)

T.test("FindByName is case-insensitive", function()
    local BL = stub.LoadAddon()
    T.eq(BL.Categories.FindByName("PRIEST"), "priest")
    T.eq(BL.Categories.FindByName("consumable"), "consumable")
    T.isnil(BL.Categories.FindByName("nothing"))
    T.isnil(BL.Categories.FindByName(nil))
end)

T.test("SetConsolidateAll flips every category and AllConsolidated reports it", function()
    local BL = stub.LoadAddon()
    local fired = 0
    BL.On("CATEGORIES_CHANGED", function() fired = fired + 1 end)
    T.falsy(BL.Categories.AllConsolidated())
    BL.Categories.SetConsolidateAll(true)
    T.truthy(BL.Categories.AllConsolidated())
    T.eq(BL.Categories.Get("other").consolidate, true)
    T.eq(fired, 1, "one event for the whole switch")
    BL.Categories.SetConsolidate("mage", false)
    T.falsy(BL.Categories.AllConsolidated())
    BL.Categories.SetConsolidateAll(false)
    T.eq(BL.Categories.Get("priest").consolidate, false)
end)

T.test("SetColor quiet fires only the colour event; the plain call fires CATEGORIES_CHANGED", function()
    local BL = stub.LoadAddon()
    local full, color = 0, 0
    BL.On("CATEGORIES_CHANGED", function() full = full + 1 end)
    BL.On("CATEGORY_COLOR_CHANGED", function(id) color = color + 1; T.eq(id, "mage") end)
    BL.Categories.SetColor("mage", { 0.1, 0.2, 0.3 }, true)
    T.eq(full, 0); T.eq(color, 1)
    BL.Categories.SetColor("mage", { 0.1, 0.2, 0.3 })
    T.eq(full, 1); T.eq(color, 1)
end)
