local stub = require("wow_stub")

T.test("Plain passes ordinary values and nils secrets", function()
    local BL = stub.LoadAddon()
    T.eq(BL.Plain("x"), "x")
    T.eq(BL.Plain(5), 5)
    T.eq(BL.Plain(false), false)
    T.isnil(BL.Plain(nil))
    T.isnil(BL.Plain(stub.MakeSecret("hidden")))
end)

T.test("PlainTable nils secret tables and non-tables", function()
    local BL = stub.LoadAddon()
    local t = { a = 1 }
    T.eq(BL.PlainTable(t), t)
    T.isnil(BL.PlainTable(stub.MakeSecretTable()))
    T.isnil(BL.PlainTable("nope"))
    T.isnil(BL.PlainTable(nil))
end)

T.test("bus fires listeners in order with arguments", function()
    local BL = stub.LoadAddon()
    local got = {}
    BL.On("PING", function(a, b) got[#got + 1] = "first:" .. a .. b end)
    BL.On("PING", function(a, b) got[#got + 1] = "second:" .. a .. b end)
    BL.Fire("PING", "x", "y")
    BL.Fire("OTHER")
    T.deq(got, { "first:xy", "second:xy" })
end)

T.test("RegisterEvent dispatches client events through the stub", function()
    local BL = stub.LoadAddon()
    local seen
    BL.RegisterEvent("GROUP_ROSTER_UPDATE", function(event, arg) seen = event .. ":" .. tostring(arg) end)
    stub.FireEvent("GROUP_ROSTER_UPDATE", 7)
    T.eq(seen, "GROUP_ROSTER_UPDATE:7")
    T.eq(stub.forbidden, 0, "never registers the combat log")
end)

T.test("ApplyDefaults deep-merges without clobbering and copies nested tables", function()
    local BL = stub.LoadAddon()
    local defaults = { a = 1, nested = { x = 1, y = { z = 2 } }, list = { 1, 2 } }
    local t = { a = 5, nested = { x = 9 } }
    BL.ApplyDefaults(t, defaults)
    T.eq(t.a, 5)
    T.eq(t.nested.x, 9)
    T.eq(t.nested.y.z, 2)
    t.nested.y.z = 99
    T.eq(defaults.nested.y.z, 2, "defaults untouched by later mutation")
    t.list[1] = 42
    T.eq(defaults.list[1], 1)
end)

T.test("InitDB creates a version-1 table with both settings scopes", function()
    local BL = stub.LoadAddon()
    T.eq(BL.DB.version, 1)
    T.eq(BL.DB.settings.iconSize, 30)
    T.eq(BL.DB.settings.debuff.iconSize, 30)
    T.eq(BL.DB.settings.hideBlizzardFrames, true)
    T.eq(type(BL.DB.overrides), "table")
    T.eq(type(BL.DB.learned), "table")
    T.eq(type(BL.DB.history), "table")
    T.eq(BL.DB.nextCustomId, 1)
    T.eq(type(BL.DB.categories), "table", "categories seeded at init")
end)

T.test("InitDB migrates a version-0 table and keeps user values", function()
    local BL = stub.LoadAddon({ before = function()
        _G.BuffLedgerDB = { settings = { iconSize = 44 }, overrides = { ["Food"] = "consumable" } }
    end })
    T.eq(BL.DB.version, 1)
    T.eq(BL.DB.settings.iconSize, 44)
    T.eq(BL.DB.settings.spacing, 4)
    T.eq(BL.DB.overrides["Food"], "consumable")
end)

T.test("GetSetting/SetSetting handle both scopes and fire SETTINGS_CHANGED", function()
    local BL = stub.LoadAddon()
    local fired = {}
    BL.On("SETTINGS_CHANGED", function(key, scope) fired[#fired + 1] = tostring(key) .. "/" .. tostring(scope) end)
    T.eq(BL.GetSetting("columns"), 10)
    T.eq(BL.GetSetting("columns", "debuff"), 10)
    BL.SetSetting("columns", 6)
    BL.SetSetting("columns", 3, "debuff")
    T.eq(BL.GetSetting("columns"), 6)
    T.eq(BL.GetSetting("columns", "buff"), 6)
    T.eq(BL.GetSetting("columns", "debuff"), 3)
    T.deq(fired, { "columns/buff", "columns/debuff" })
end)

T.test("FormatTime matches the client's abbreviations", function()
    local BL = stub.LoadAddon()
    T.eq(BL.FormatTime(nil), "")
    T.eq(BL.FormatTime(0), "")
    T.eq(BL.FormatTime(-3), "")
    T.eq(BL.FormatTime(9.4), "9s")
    T.eq(BL.FormatTime(59), "59s")
    T.eq(BL.FormatTime(60), "1m")
    T.eq(BL.FormatTime(3599), "59m")
    T.eq(BL.FormatTime(3600), "1h")
    T.eq(BL.FormatTime(86400), "1d")
    T.eq(BL.FormatTime(90000), "1d")
end)

T.test("ClassToken lowercases the class file token and guards secrets", function()
    local BL = stub.LoadAddon()
    stub.SetUnits({ player = { name = "Me", class = "HUNTER" }, party1 = { name = "Bob", class = "PRIEST" } })
    T.eq(BL.ClassToken("party1"), "priest")
    T.eq(BL.ClassToken("player"), "hunter")
    T.isnil(BL.ClassToken("party9"))
    T.isnil(BL.ClassToken(nil))
    T.noerror(function() T.isnil(BL.ClassToken(stub.MakeSecret("party1"))) end)
end)

T.test("Print goes to the chat frame with the accent prefix", function()
    local BL = stub.LoadAddon()
    BL.Print("hello")
    T.eq(stub.LastChat(), "|cffa335eeBuffLedger:|r hello")
end)
